services:
  db:
    image: mysql:8.4
    container_name: cp1-mysql
    environment:
      MYSQL_DATABASE: cp1
      MYSQL_USER: cp1
      MYSQL_PASSWORD: cp1
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - dbdata:/var/lib/mysql

  api:
    build: .
    container_name: cp1-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: cp1
      DB_USER: cp1
      DB_PASS: cp1
    ports:
      - "8080:8080"

volumes:
  dbdata:
